version: "3"

networks:
  filmscanner:

volumes:
  db-filmscanner:

services:
  postgres:
    image: postgres:13
    hostname: postgres
    restart: unless-stopped
    container_name: filmscanner-db
    environment:
      POSTGRES_DB: filmscanner
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5442:5432
    volumes:
      - db-filmscanner:/var/lib/postgresql/data
    networks:
      - filmscanner
