name: Docker Image CI

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
    - 
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: docker buildx build . --file Dockerfile --tag my-image-name:$(date +%s) --platform linux/amd64
