name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3.3.1
      with:
          buildx-version: latest
          qemu-version: latest
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: docker buildx build . --file Dockerfile --tag my-image-name:$(date +%s) --platform linux/amd64,linux/arm/v7,linux/arm64
    - name: Publish to docker with buildx as latest
      run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            -t $GITHUB_REPOSITORY:latest \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VSC_REF=$(echo ${GITHUB_SHA} | cut -c1-8) \
            .
